version: 2.17
jobs:
  build:
    working_directory: ~/hello
    docker:
      - image: circleci/node:15.14.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
      - run:
          name: build-package
          command: npm run export
      - run:
          name: zip-package
          command: zip -r build.zip out
      - run:
          name: Deploy over SSH
          command: scp -r -o  StrictHostKeyChecking=no -P 25088 ./build.zip rw4crpqo@lhcp3181.webapps.net:/home/rw4crpqo/public_html;
      - run:
          name: enter-server
          command: |
            ssh -p 25088 rw4crpqo@lhcp3181.webapps.net |
            cd public_html |
            unzip build.zip |
            mv -v ./out/* ./ |
            exit

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build